In [1]:
# Load libraries
from sklearn import datasets
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

os.getcwd()

NameError: name 'os' is not defined

In [63]:
import sqlite3
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

conn = sqlite3.connect(r"/Users/claire/Documents/WP/cs185c/project/FPA_FOD_20170508 (1).sqlite")

df = pd.read_sql_query("Select * from classifed_weather_data_dg_tmp WHERE isFire = 1 LIMIT 1000 ", conn)
df

,level_0,index,stn,wban,temp,count_temp,dewp,count_dewp,slp,count_slp,...,flag_prcp,sndp,fog,rain_drizzle,snow_ice_pellets,hail,thunder,tornado_funnel_cloud,date,isFire
0,749175,749175,690150,93121,59.0,24,27.4,24,1011.6,24,...,I,999.9,0,0,0,0,0,0,2014-04-05,1
1,885411,885411,720193,99999,35.8,24,29.0,24,9999.9,0,...,I,999.9,0,0,0,0,0,0,2014-01-19,1
2,885440,885440,720193,99999,64.7,24,31.6,24,9999.9,0,...,I,999.9,0,0,0,0,0,0,2014-04-30,1
3,885443,885443,720193,99999,67.7,24,39.6,24,9999.9,0,...,I,999.9,0,0,0,0,0,0,2014-05-15,1
4,885446,885446,720193,99999,65.8,24,36.5,24,9999.9,0,...,I,999.9,0,0,0,0,0,0,2014-05-25,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2760286,2760286,723895,23149,85.4,24,43.1,24,9999.9,0,...,I,999.9,0,0,0,0,0,0,2014-07-05,1
996,2760290,2760290,723895,23149,84.8,24,55.3,24,9999.9,0,...,I,999.9,0,0,0,0,0,0,2014-07-16,1
997,2760292,2760292,723895,23149,87.0,24,54.9,24,9999.9,0,...,I,999.9,0,0,0,0,0,0,2014-07-30,1
998,2760293,2760293,723895,23149,87.8,24,50.6,24,9999.9,0,...,I,999.9,0,0,0,0,0,0,2014-08-01,1
999,2760294,2760294,723895,23149,81.9,24,53.4,24,9999.9,0,...,I,999.9,0,0,0,0,0,0,2014-08-11,1

array([[59.0, 27.4, 1011.6, ..., '0', '0', '0'],
       [35.8, 29.0, 9999.9, ..., '0', '0', '0'],
       [64.7, 31.6, 9999.9, ..., '0', '0', '0'],
       ...,
       [72.9, 34.2, 9999.9, ..., '0', '0', '0'],
       [80.4, 41.0, 9999.9, ..., '0', '0', '0'],
       [82.9, 38.7, 9999.9, ..., '0', '0', '0']], dtype=object)

In [62]:
dfNoFire = pd.read_sql_query("Select * from classifed_weather_data_dg_tmp WHERE isFire = 0 LIMIT 5000 ", conn)
dfNoFire

,level_0,index,stn,wban,temp,count_temp,dewp,count_dewp,slp,count_slp,...,flag_prcp,sndp,fog,rain_drizzle,snow_ice_pellets,hail,thunder,tornado_funnel_cloud,date,isFire
0,0,0,765560,99999,79.0,19,64.4,19,1013.8,9,...,G,999.9,0,0,0,0,0,0,2014-05-27,0
1,1,1,765560,99999,77.2,18,69.5,18,1010.0,9,...,G,999.9,0,1,0,0,1,0,2014-06-07,0
2,2,2,765560,99999,77.8,16,71.4,16,1011.0,9,...,G,999.9,0,1,0,0,1,0,2014-06-08,0
3,3,3,765560,99999,77.3,19,66.7,19,1008.5,9,...,G,999.9,0,1,0,0,1,0,2014-06-10,0
4,4,4,765560,99999,77.6,19,69.6,19,1012.7,9,...,G,999.9,0,0,0,0,0,0,2014-06-24,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4995,4995,782240,99999,64.2,24,50.4,24,9999.9,0,...,I,999.9,0,0,0,0,0,0,2014-01-19,0
4996,4996,4996,782240,99999,65.8,24,56.5,24,9999.9,0,...,None,999.9,0,1,0,0,0,0,2014-01-22,0
4997,4997,4997,782240,99999,62.5,24,52.1,24,9999.9,0,...,I,999.9,0,0,0,0,0,0,2014-01-23,0
4998,4998,4998,782240,99999,75.0,24,68.6,24,9999.9,0,...,None,999.9,0,1,0,0,0,0,2014-01-31,0
4999,4999,4999,782240,99999,72.8,24,66.2,18,9999.9,0,...,I,999.9,1,0,0,0,0,0,2014-02-06,0

In [64]:
bigdata = df.append(dfNoFire, ignore_index=True)
bigdata

,level_0,index,stn,wban,temp,count_temp,dewp,count_dewp,slp,count_slp,...,flag_prcp,sndp,fog,rain_drizzle,snow_ice_pellets,hail,thunder,tornado_funnel_cloud,date,isFire
0,749175,749175,690150,93121,59.0,24,27.4,24,1011.6,24,...,I,999.9,0,0,0,0,0,0,2014-04-05,1
1,885411,885411,720193,99999,35.8,24,29.0,24,9999.9,0,...,I,999.9,0,0,0,0,0,0,2014-01-19,1
2,885440,885440,720193,99999,64.7,24,31.6,24,9999.9,0,...,I,999.9,0,0,0,0,0,0,2014-04-30,1
3,885443,885443,720193,99999,67.7,24,39.6,24,9999.9,0,...,I,999.9,0,0,0,0,0,0,2014-05-15,1
4,885446,885446,720193,99999,65.8,24,36.5,24,9999.9,0,...,I,999.9,0,0,0,0,0,0,2014-05-25,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,4995,4995,782240,99999,64.2,24,50.4,24,9999.9,0,...,I,999.9,0,0,0,0,0,0,2014-01-19,0
5996,4996,4996,782240,99999,65.8,24,56.5,24,9999.9,0,...,None,999.9,0,1,0,0,0,0,2014-01-22,0
5997,4997,4997,782240,99999,62.5,24,52.1,24,9999.9,0,...,I,999.9,0,0,0,0,0,0,2014-01-23,0
5998,4998,4998,782240,99999,75.0,24,68.6,24,9999.9,0,...,None,999.9,0,1,0,0,0,0,2014-01-31,0
5999,4999,4999,782240,99999,72.8,24,66.2,18,9999.9,0,...,I,999.9,1,0,0,0,0,0,2014-02-06,0

In [65]:
from sklearn.preprocessing import StandardScaler

features = ['temp', 'dewp', 'slp', 'stp', 'visib', 'wdsp', 'mxpsd', 'gust', 'max','min', 'prcp', 'sndp', 'fog', 'rain_drizzle', 'snow_ice_pellets', 'hail', 'thunder', 'tornado_funnel_cloud']

# Separating out the features
X = bigdata.loc[:, features].values



X

array([[59.0, 27.4, 1011.6, ..., '0', '0', '0'],
       [35.8, 29.0, 9999.9, ..., '0', '0', '0'],
       [64.7, 31.6, 9999.9, ..., '0', '0', '0'],
       ...,
       [62.5, 52.1, 9999.9, ..., '0', '0', '0'],
       [75.0, 68.6, 9999.9, ..., '0', '0', '0'],
       [72.8, 66.2, 9999.9, ..., '0', '0', '0']], dtype=object)

In [66]:
# Separating out the 'isFire' as target
y = bigdata.loc[:,['isFire']].values.ravel()
y

array([1, 1, 1, ..., 0, 0, 0])

In [69]:
# Standardizing the features
X = StandardScaler().fit_transform(X)

X

array([[-1.28306813, -0.19846661, -0.58390063, ..., -0.02236627,
        -0.24509319,  0.        ],
       [-3.55610365, -0.19754759,  1.7137694 , ..., -0.02236627,
        -0.24509319,  0.        ],
       [-0.72460682, -0.19605418,  1.7137694 , ..., -0.02236627,
        -0.24509319,  0.        ],
       ...,
       [-0.94015329, -0.18427923,  1.7137694 , ..., -0.02236627,
        -0.24509319,  0.        ],
       [ 0.28454257, -0.17480182,  1.7137694 , ..., -0.02236627,
        -0.24509319,  0.        ],
       [ 0.0689961 , -0.17618035,  1.7137694 , ..., -0.02236627,
        -0.24509319,  0.        ]])

In [70]:
# Create an LDA that will reduce the data down to 1 feature
lda = LinearDiscriminantAnalysis(n_components=1)

# run an LDA and use it to transform the features
X_lda = lda.fit(X, y).transform(X)
X_lda

/Users/claire/opt/anaconda3/lib/python3.7/site-packages/sklearn/discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")

array([[2.42126584],
       [2.33262245],
       [3.35839216],
       ...,
       [1.12248823],
       [0.03778629],
       [0.48306763]])

In [71]:

lda_df = pd.DataFrame(data = X_lda
             , columns = ['lda component'])

lda_df

      lda component
0          2.421266
1          2.332622
2          3.358392
3          3.226571
4          3.300719
...             ...
5995       1.045641
5996       2.758361
5997       1.122488
5998       0.037786
5999       0.483068

[6000 rows x 1 columns]

In [36]:
# Separating out the features
#X_neural = lda_df
#X

array([[-0.03617286, -0.23230754, -0.69576087, ..., -0.02014312,
        -0.19486547,  0.        ],
       [-1.07422899, -0.23155018,  1.43838583, ..., -0.02014312,
        -0.19486547,  0.        ],
       [ 0.21886679, -0.23031947,  1.43838583, ..., -0.02014312,
        -0.19486547,  0.        ],
       ...,
       [-0.78786868, -0.22979878,  1.43838583, ..., -0.02014312,
        -0.19486547,  0.        ],
       [-0.25989186, -0.22544395,  1.43838583, ..., -0.02014312,
        -0.19486547,  0.        ],
       [-0.25541748, -0.22572796,  1.43838583, ..., -0.02014312,
        -0.19486547,  0.        ]])

In [72]:

# Standardizing the features
X_lda = StandardScaler().fit_transform(lda_df)

X_lda

array([[1.78633399],
       [1.72093568],
       [2.4777164 ],
       ...,
       [0.8281366 ],
       [0.02787754],
       [0.35639215]])

In [73]:
y = bigdata.loc[:,['isFire']].values
y

array([[1],
       [1],
       [1],
       ...,
       [0],
       [0],
       [0]])

In [74]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_lda, y, test_size=0.3)
print(X_train.shape,  X_test.shape, y_train.shape,  y_test.shape)

(4200, 1) (1800, 1) (4200, 1) (1800, 1)

In [75]:
from keras import Sequential
from keras.layers import Dense

In [76]:
classifier = Sequential()
#First Hidden Layer
classifier.add(Dense(4, activation='relu', kernel_initializer='random_normal', input_dim=1))
#Second  Hidden Layer
classifier.add(Dense(4, activation='relu', kernel_initializer='random_normal'))
#Output Layer
classifier.add(Dense(1, activation='sigmoid', kernel_initializer='random_normal'))

In [77]:
#Compiling the neural network
classifier.compile(optimizer ='adam',loss='binary_crossentropy', metrics =['accuracy'])

In [78]:
#Fitting the data to the training dataset
classifier.fit(X_train,y_train, batch_size=100, epochs=100)

Epoch 1/100
4200/4200 [==============================] - 0s 78us/step - loss: 0.6855 - accuracy: 0.8117
Epoch 2/100
4200/4200 [==============================] - 0s 15us/step - loss: 0.6653 - accuracy: 0.8305
Epoch 3/100
4200/4200 [==============================] - 0s 15us/step - loss: 0.6343 - accuracy: 0.8305
Epoch 4/100
4200/4200 [==============================] - 0s 15us/step - loss: 0.5878 - accuracy: 0.8314
Epoch 5/100
4200/4200 [==============================] - 0s 16us/step - loss: 0.5272 - accuracy: 0.8586
Epoch 6/100
4200/4200 [==============================] - 0s 18us/step - loss: 0.4590 - accuracy: 0.8936
Epoch 7/100
4200/4200 [==============================] - 0s 16us/step - loss: 0.3942 - accuracy: 0.9050
Epoch 8/100
4200/4200 [==============================] - 0s 17us/step - loss: 0.3412 - accuracy: 0.9126
Epoch 9/100
4200/4200 [==============================] - 0s 16us/step - loss: 0.3030 - accuracy: 0.9119
Epoch 10/100
4200/4200 [==============================] - 0s 16us/step - loss: 0.2780 - accuracy: 0.9110
Epoch 11/100
4200/4200 [==============================] - 0s 16us/step - loss: 0.2622 - accuracy: 0.9098
Epoch 12/100
4200/4200 [==============================] - 0s 20us/step - loss: 0.2526 - accuracy: 0.9100
Epoch 13/100
4200/4200 [==============================] - 0s 24us/step - loss: 0.2471 - accuracy: 0.9107
Epoch 14/100
4200/4200 [==============================] - 0s 24us/step - loss: 0.2439 - accuracy: 0.9107
Epoch 15/100
4200/4200 [==============================] - 0s 16us/step - loss: 0.2420 - accuracy: 0.9107
Epoch 16/100
4200/4200 [==============================] - 0s 14us/step - loss: 0.2411 - accuracy: 0.9102
Epoch 17/100
4200/4200 [==============================] - 0s 15us/step - loss: 0.2404 - accuracy: 0.9102
Epoch 18/100
4200/4200 [==============================] - 0s 24us/step - loss: 0.2399 - accuracy: 0.9110
Epoch 19/100
4200/4200 [==============================] - 0s 22us/step - loss: 0.2397 - accuracy: 0.9112
Epoch 20/100
4200/4200 [==============================] - 0s 24us/step - loss: 0.2394 - accuracy: 0.9112
Epoch 21/100
4200/4200 [==============================] - 0s 22us/step - loss: 0.2392 - accuracy: 0.9110
Epoch 22/100
4200/4200 [==============================] - 0s 21us/step - loss: 0.2391 - accuracy: 0.9110
Epoch 23/100
4200/4200 [==============================] - 0s 17us/step - loss: 0.2389 - accuracy: 0.9112
Epoch 24/100
4200/4200 [==============================] - 0s 20us/step - loss: 0.2389 - accuracy: 0.9110
Epoch 25/100
4200/4200 [==============================] - 0s 24us/step - loss: 0.2388 - accuracy: 0.9119
Epoch 26/100
4200/4200 [==============================] - 0s 20us/step - loss: 0.2386 - accuracy: 0.9107
Epoch 27/100
4200/4200 [==============================] - 0s 20us/step - loss: 0.2386 - accuracy: 0.9112
Epoch 28/100
4200/4200 [==============================] - 0s 20us/step - loss: 0.2384 - accuracy: 0.9112
Epoch 29/100
4200/4200 [==============================] - 0s 15us/step - loss: 0.2382 - accuracy: 0.9114
Epoch 30/100
4200/4200 [==============================] - 0s 23us/step - loss: 0.2381 - accuracy: 0.9107
Epoch 31/100
4200/4200 [==============================] - 0s 24us/step - loss: 0.2379 - accuracy: 0.9112
Epoch 32/100
4200/4200 [==============================] - 0s 16us/step - loss: 0.2378 - accuracy: 0.9107
Epoch 33/100
4200/4200 [==============================] - 0s 15us/step - loss: 0.2379 - accuracy: 0.9117
Epoch 34/100
4200/4200 [==============================] - 0s 14us/step - loss: 0.2377 - accuracy: 0.9107
Epoch 35/100
4200/4200 [==============================] - 0s 14us/step - loss: 0.2376 - accuracy: 0.9121
Epoch 36/100
4200/4200 [==============================] - 0s 16us/step - loss: 0.2375 - accuracy: 0.9114
Epoch 37/100
4200/4200 [==============================] - 0s 16us/step - loss: 0.2374 - accuracy: 0.9112
Epoch 38/100
4200/4200 [==============================] - 0s 17us/step - loss: 0.2375 - accuracy: 0.9114
Epoch 39/100
4200/4200 [==============================] - 0s 49us/step - loss: 0.2373 - accuracy: 0.9107
Epoch 40/100
4200/4200 [==============================] - 0s 20us/step - loss: 0.2373 - accuracy: 0.9110
Epoch 41/100
4200/4200 [==============================] - 0s 19us/step - loss: 0.2371 - accuracy: 0.9119
Epoch 42/100
4200/4200 [==============================] - 0s 21us/step - loss: 0.2371 - accuracy: 0.9124
Epoch 43/100
4200/4200 [==============================] - 0s 25us/step - loss: 0.2371 - accuracy: 0.9112
Epoch 44/100
4200/4200 [==============================] - 0s 30us/step - loss: 0.2370 - accuracy: 0.9119
Epoch 45/100
4200/4200 [==============================] - 0s 28us/step - loss: 0.2370 - accuracy: 0.9112
Epoch 46/100
4200/4200 [==============================] - 0s 20us/step - loss: 0.2369 - accuracy: 0.9121
Epoch 47/100
4200/4200 [==============================] - 0s 30us/step - loss: 0.2368 - accuracy: 0.9121
Epoch 48/100
4200/4200 [==============================] - 1s 126us/step - loss: 0.2368 - accuracy: 0.9119
Epoch 49/100
4200/4200 [==============================] - 0s 48us/step - loss: 0.2368 - accuracy: 0.9117
Epoch 50/100
4200/4200 [==============================] - 0s 18us/step - loss: 0.2371 - accuracy: 0.9119
Epoch 51/100
4200/4200 [==============================] - 0s 39us/step - loss: 0.2368 - accuracy: 0.9121
Epoch 52/100
4200/4200 [==============================] - 0s 22us/step - loss: 0.2369 - accuracy: 0.9119
Epoch 53/100
4200/4200 [==============================] - 0s 31us/step - loss: 0.2366 - accuracy: 0.9124
Epoch 54/100
4200/4200 [==============================] - 0s 33us/step - loss: 0.2367 - accuracy: 0.9119
Epoch 55/100
4200/4200 [==============================] - 0s 16us/step - loss: 0.2365 - accuracy: 0.9126
Epoch 56/100
4200/4200 [==============================] - 0s 14us/step - loss: 0.2365 - accuracy: 0.9117
Epoch 57/100
4200/4200 [==============================] - 0s 25us/step - loss: 0.2364 - accuracy: 0.9124
Epoch 58/100
4200/4200 [==============================] - 0s 17us/step - loss: 0.2365 - accuracy: 0.9117
Epoch 59/100
4200/4200 [==============================] - 0s 15us/step - loss: 0.2362 - accuracy: 0.9133
Epoch 60/100
4200/4200 [==============================] - 0s 17us/step - loss: 0.2363 - accuracy: 0.9129
Epoch 61/100
4200/4200 [==============================] - 0s 25us/step - loss: 0.2362 - accuracy: 0.9117
Epoch 62/100
4200/4200 [==============================] - 0s 25us/step - loss: 0.2361 - accuracy: 0.9126
Epoch 63/100
4200/4200 [==============================] - 0s 25us/step - loss: 0.2361 - accuracy: 0.9121
Epoch 64/100
4200/4200 [==============================] - 0s 20us/step - loss: 0.2360 - accuracy: 0.9119
Epoch 65/100
4200/4200 [==============================] - 0s 20us/step - loss: 0.2360 - accuracy: 0.9129
Epoch 66/100
4200/4200 [==============================] - 0s 21us/step - loss: 0.2359 - accuracy: 0.9131
Epoch 67/100
4200/4200 [==============================] - 0s 20us/step - loss: 0.2359 - accuracy: 0.9112
Epoch 68/100
4200/4200 [==============================] - 0s 17us/step - loss: 0.2358 - accuracy: 0.9129
Epoch 69/100
4200/4200 [==============================] - 0s 21us/step - loss: 0.2358 - accuracy: 0.9126
Epoch 70/100
4200/4200 [==============================] - 0s 20us/step - loss: 0.2356 - accuracy: 0.9129
Epoch 71/100
4200/4200 [==============================] - 0s 23us/step - loss: 0.2355 - accuracy: 0.9129
Epoch 72/100
4200/4200 [==============================] - 0s 22us/step - loss: 0.2355 - accuracy: 0.9119
Epoch 73/100
4200/4200 [==============================] - 0s 15us/step - loss: 0.2355 - accuracy: 0.9129
Epoch 74/100
4200/4200 [==============================] - 0s 14us/step - loss: 0.2356 - accuracy: 0.9126
Epoch 75/100
4200/4200 [==============================] - 0s 12us/step - loss: 0.2354 - accuracy: 0.9131
Epoch 76/100
4200/4200 [==============================] - 0s 14us/step - loss: 0.2353 - accuracy: 0.9129
Epoch 77/100
4200/4200 [==============================] - 0s 17us/step - loss: 0.2353 - accuracy: 0.9133
Epoch 78/100
4200/4200 [==============================] - 0s 24us/step - loss: 0.2354 - accuracy: 0.9119
Epoch 79/100
4200/4200 [==============================] - 0s 24us/step - loss: 0.2352 - accuracy: 0.9131
Epoch 80/100
4200/4200 [==============================] - 0s 16us/step - loss: 0.2352 - accuracy: 0.9126
Epoch 81/100
4200/4200 [==============================] - 0s 13us/step - loss: 0.2353 - accuracy: 0.9119
Epoch 82/100
4200/4200 [==============================] - 0s 12us/step - loss: 0.2352 - accuracy: 0.9133
Epoch 83/100
4200/4200 [==============================] - 0s 12us/step - loss: 0.2351 - accuracy: 0.9133
Epoch 84/100
4200/4200 [==============================] - 0s 13us/step - loss: 0.2350 - accuracy: 0.9133
Epoch 85/100
4200/4200 [==============================] - 0s 12us/step - loss: 0.2350 - accuracy: 0.9131
Epoch 86/100
4200/4200 [==============================] - 0s 13us/step - loss: 0.2351 - accuracy: 0.9136
Epoch 87/100
4200/4200 [==============================] - 0s 25us/step - loss: 0.2350 - accuracy: 0.9133
Epoch 88/100
4200/4200 [==============================] - 0s 21us/step - loss: 0.2350 - accuracy: 0.9131
Epoch 89/100
4200/4200 [==============================] - 0s 19us/step - loss: 0.2351 - accuracy: 0.9124
Epoch 90/100
4200/4200 [==============================] - 0s 17us/step - loss: 0.2351 - accuracy: 0.9124
Epoch 91/100
4200/4200 [==============================] - 0s 15us/step - loss: 0.2349 - accuracy: 0.9131
Epoch 92/100
4200/4200 [==============================] - 0s 13us/step - loss: 0.2349 - accuracy: 0.9131
Epoch 93/100
4200/4200 [==============================] - 0s 12us/step - loss: 0.2350 - accuracy: 0.9124
Epoch 94/100
4200/4200 [==============================] - 0s 13us/step - loss: 0.2349 - accuracy: 0.9131
Epoch 95/100
4200/4200 [==============================] - 0s 13us/step - loss: 0.2349 - accuracy: 0.9131
Epoch 96/100
4200/4200 [==============================] - 0s 12us/step - loss: 0.2349 - accuracy: 0.9126
Epoch 97/100
4200/4200 [==============================] - 0s 12us/step - loss: 0.2349 - accuracy: 0.9131
Epoch 98/100
4200/4200 [==============================] - 0s 12us/step - loss: 0.2348 - accuracy: 0.9133
Epoch 99/100
4200/4200 [==============================] - 0s 12us/step - loss: 0.2349 - accuracy: 0.9131
Epoch 100/100
4200/4200 [==============================] - 0s 17us/step - loss: 0.2349 - accuracy: 0.9133

In [48]:
classifier.evaluate(X_test, y_test)

3699/3699 [==============================] - 0s 72us/step

[0.3268452176663578, 0.8951067924499512]

In [79]:
# make class predictions for the testing set
y_pred_class = classifier.predict(X_test)
y_pred_class

array([[0.00152847],
       [0.04198292],
       [0.04851827],
       ...,
       [0.01584485],
       [0.0371888 ],
       [0.38851407]], dtype=float32)

In [80]:
# IMPORTANT: first argument is true values, second argument is predicted values
# this produces a 2x2 numpy array (matrix)
print(metrics.confusion_matrix(y_test, y_pred_class))

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [54]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

ValueError: Classification metrics can't handle a mix of binary and continuous targets